tasks:
  pesquisa_de_noticias:
    description: >
      Pesquise e colete de 5 a 10 artigos e notícias recentes sobre o tópico: {topic}.
      Concentre-se em fontes de notícias confiáveis. Sua saída final deve ser uma
      lista de URLs e o texto bruto de cada fonte.
    expected_output: >
      Uma lista formatada contendo o URL e o conteúdo textual de cada artigo encontrado.

  analise_e_sumarizacao_factual:
    description: >
      Analise o conteúdo bruto coletado na tarefa anterior. Para cada artigo,
      identifique os fatos principais e crie um resumo conciso e objetivo.
      A saída deve ser uma lista de resumos factuais.
    expected_output: >
      Uma lista de resumos em bullet points, cada um representando o núcleo factual
      de um artigo analisado.

  expansao_com_perspectivas:
    description: >
      Com base nos resumos factuais, procure por conteúdo que ofereça diferentes
      perspectivas sobre o {topic}. Encontre artigos de opinião, análises críticas
      ou posts de blog que debatam o tema. Forneça o link e uma breve descrição
      do ponto de vista de cada um.
    expected_output: >
      Uma lista curada de conteúdo complementar, cada item contendo um link e uma
      frase que descreve a perspectiva ou análise oferecida.

  filtro_de_alinhamento_com_constituicao:
    description: >
      Avalie todo o conteúdo produzido (resumos factuais e conteúdo expandido)
      com base na seguinte constituição definida pelo usuário: {constitution}.
      Garanta que o material seja balanceado, evite extremismos e esteja alinhado
      com os princípios. Rejeite qualquer conteúdo que viole essas diretrizes.
      Sua saída final é o conjunto de conteúdo aprovado.
    expected_output: >
      O conjunto consolidado e filtrado de resumos factuais e links de expansão
      que foram aprovados por estarem em conformidade com a constituição.

  busca_de_imagem:
    description: >
      Com base no resumo final do conteúdo, encontre UMA imagem de alta qualidade
      e relevante para o tópico '{topic}'. A imagem deve ser visualmente
      atraente e de uso livre.
    expected_output: >
      O URL da melhor imagem encontrada.

  compilacao_final_em_markdown:
    description: >
      Receba o conteúdo final aprovado pelo Agente Guardião e imagem (URL) do Curador de Imagens
      e organize-o em um arquivo Markdown bem estruturado. O arquivo deve ter seções claras:
      'Principais Notícias (Resumo Factual)', 'Diferentes Perspectivas e Análises'.
      Use formatação Markdown para títulos, listas e links.
    expected_output: >
      Um único arquivo de texto em formato Markdown chamado 'resumo_{topic}.md',
      contendo todo o conteúdo formatado de maneira coesa e pronta para ser lida.
    output_file: 'resumo_do_topico.md'